nodeLinker: node-modules

packageExtensions:
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
  css-loader@*:
    dependencies:
      webpack: "*"
  eslint-config-react-app@*:
    dependencies:
      eslint: "*"
  eslint-plugin-flowtype@*:
    dependencies:
      "@babel/core": "*"
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
  react-dev-utils@*:
    dependencies:
      webpack: "*"
  tailwindcss@*:
    dependencies:
      autoprefixer: "*"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
