const en = {
  
  'pages': 'Pages',
  'articles': 'Articles',
  'locale': 'Locale',
  'locales': 'Locales',
  'tag': 'Tag',
  'links': 'Links',
  'releases': 'Releases',
  'options': 'Options',

  'value': 'Value',
  'date': 'Date',
  'order': 'Order',
  'description': 'Description',
  'name': 'Name',

  'delete': 'Delete',
  'download': 'Download JSON',
  'disable': 'Disable',
  'status': 'Status',
  'created': 'Created',
  'modified': 'Modified',
  'rename': 'Rename',
  'reorder': 'Re-order',
  'remove': 'Remove',
  
  'search.field.placeholder': 'Enter search keyword',
  'search.results.title': 'Search results',
  'search.field.label': 'Search',
  
  'activities.title': 'Activities',
  'activities.desc': 'Create, view, and navigate site resources',
  'activities.article.title': 'Article',
  'activities.article.desc': 'An Article is like a category: It groups Pages, Links, and Services together under one roof.',
  'activities.locale.title': 'Locale',
  'activities.locale.desc': 'Locales are your languages: Add, activate, and deactivate sitewide locales here. You can add a Page in a specific language if you have defined a locale for that page.',
  'activities.page.title': 'Page',
  'activities.page.desc': 'A Page is one content file within an Article. It represents one language and any links / workflows that are associated with an Article. It is written using Markdown syntax. ',
  'activities.link.title': 'Hyperlink',
  'activities.link.desc': 'A Hyperlink will connect users to webpages you own, webpages of other organisations, and your telephone numbers.',
  'activities.release.title': 'Release',
  'activities.release.desc': 'A Release is a snapshot of all site content at one certain point of time. Use this for testing, prouduction, or backup purposes.',
  'activities.migration.title': 'Migrations',
  'migration.create': 'Migrate data',
  'activities.migration.desc': 'Import site data as a JSON file for restoring site from a backup, content updates, etc.',
  'activities.templates.title': 'Templates',
  'activities.templates.desc': 'Use templates to customise and standardise a page default Markdown content and/or structure. Templates can be applied to new pages upon creation. ',
   
  'templates': 'Templates',
  'template.name': 'Template name',
  'template.name.desc': 'User-given name for this template',
  'template.create': 'Create template',
  'template.edit': 'Edit Template',
  'template.type': 'Template type',
  'template.page': 'Page template',
  'template.page.desc': 'This template can be applied to a new page upon creation of that page.',
  'template.description': 'Write templates in Markdown to apply to your pages and content. Templates help speed up your development and unify your content structure.',
  'template.desc': 'Description',
  'template.description.desc': 'Additional information to help identify the use cases of this template',
  'template.delete': 'Delete template',
  'template.delete.message': 'This template will be permanently removed from the application',

  'templates.templatesview.description': 'Templates view description!',
  'templates.templatesview.note': 'Description',
  'templates.intro': 'Remember to use a Markdown Level 1 Heading (# My Heading 1) when composing your templates.',

  'services': 'Services',
  'services.create': 'Create service',
  'services.desc': 'Connect your forms and other integrations to your content with the Wrench and Dialob workflows',
  'services.add': 'Add a service',
  'services.change': 'Change existing services',
  'services.edit': 'Edit service',

  'services.technicalname': 'Workflow name',
  'services.technicalname.description': 'Flow name as defined in the Wrench',
  'services.selected': 'Selected services',
  'services.devmode.helper': 'If Development mode is active, this service will only appear in the development environment for testing. It will not be included in production releases.',
  'services.devmode': 'Development mode',
  'services.delete': 'Permanently delete this service?',

  'toolbar.search': 'Search',
  'toolbar.activities': 'Activities',
  'toolbar.help': 'Help and user documentation',
  'toolbar.services': 'Services',
  'toolbar.import': 'Import data',
  
  'link.type.internal': 'Internal',
  'link.type.external': 'External',
  'link.type.phone': 'Phone number',
  'link.search.title': 'Search links by value',
  'link.value': 'Link value',
  
  'sitelocale.label.select.alreadyDefined': 'Cannot add because this locale is already defined',
  'sitelocale.label.table.editLocaleValue': 'Edit locale value',
  'locales.label.table.title': 'Locale labels',
  'locales.label.title.helper': 'At least one language code (locale) + locale label value is required',
  'locales.label.table.value': 'Locale label values',

  'transferlist.noItemsSelected': 'No items selected',
  'transferlist.search': 'Search',
  'transferlist.noSearchResults': 'No search results found',

  'explorer.tabs.search': 'Search',
  'explorer.tabs.articles': 'Articles',
  'explorer.tabs.links': 'Links',
  'explorer.tabs.services': 'Services',

  'imports': 'Imports',
  'imports.select': 'Select a file to import',
  'imports.import.action': 'Import selected',
  
  'article.order': 'Article order number',
  'article.select': 'Select Articles',
  'article.links.selectedlinks': 'Selected links',
  'article.composer.title': 'Create new Article',
  'article.composer.parent': 'Parent Article',
  'article.parent.helper': 'If a Parent article is selected, this article will live inside this parent, like a file inside a folder does.',
  'article.composer.parent.unselected': 'No parent article',
  'article.create': 'Create article',
  'article.name': 'Article name',
  'article.delete.title': 'Delete article',
  'article.delete': 'Deleting this article will remove it and its associated pages globally from the application.',
  'article.edit.title': 'Edit article',
  'article.edit.parent': 'Parent article',
  'article.edit.orderhelper': 'Three-digit number for ordering purposes',

  'articleservices': 'Article services: {name}',
  'articlelinks': 'Article links: {name}',
  'article.composer.orderhelper': 'The lower the number, the higher up this article will appear in your portal UI Topic Menu.  Example: 000 will be the first Topic menu item, while 999 will be the last.',
  'allarticles': 'Select all articles',
  'allarticles.individual': 'De-select all articles',
  'add.allarticles.link.help': 'This link will be added to (or removed from) all articles. Any previous link-article associations will be lost once this change has been applied',
  'add.allarticles.service.help': 'This service will be added to (or removed from) all articles. Any previous service-article associations will be lost once this change has been applied.',
  
  'button.cancel': 'Cancel',
  'button.create': 'Create',
  'button.add': 'Add',
  'button.update': 'Update',
  'button.delete': 'Continue and delete',
  'button.disable': 'Continue and disable',
  'button.enable': 'Continue and enable',
  'button.remove': 'Continue and remove',
  'button.apply': 'Apply changes',
  'button.releasegraph': 'Graph',
  
  'button.view.all.locales': 'View locales',
  'button.view.all.releases': 'View releases',
  'button.view.all.templates': 'View templates',

  'links.message': 'Expand rows to view Link - Article associations',
  
  'link.article.add.title': 'Add link to an Article',
  'link.article.select': 'Select Article',
  'link.type': 'Type',
  'link.url': 'URL / value',
  'link.locale.all': 'All locales',
  'link.content': 'Link URL / path',
  'link.composer.title': 'Create a new link',
  'link.composer.descriptionlabel': 'Description',
  'link.composer.descriptionhelper': 'Text that the user will see',
  'link.composer.valuehelper': 'URL / path of link (http://www.example.com)',
  'link.edit.title': 'Edit link',
  'link.delete.title': 'Permanently delete this link?',
  'link.delete': 'Deleting this link will permanently remove it from the application, and all associations with Articles/Pages will be lost.',
  'link.removepage.title': 'Remove this link?',
  'link.removepage': 'Removing the link only removes its association with this article. To delete this item permanently, click the Delete icon.',
  'link.options': 'Link options',
  'link.options.add': 'Add links to article',
  'resource.edit.links': 'Edit links',
  'links.change': 'Change existing links',
  'link.create': 'Create new link',

  'locale.create': 'Create locale',
  'locale.disable.title': 'Disable this locale?',
  'locale.enable.title': 'Enable this locale?',
  'locale.disable': 'Any Pages using this locale will be hidden on the UI. Pages can still be edited.',
  'locale.enable': 'All Pages using this locale will be displayed on the UI.',
  'locale.composer.title': 'Create a new locale',
  'locale.composer.placeholder': 'Two-letter language code',
  'locale.composer.helper': 'Two-letter language codes designate the content language. Common examples: en = English, fi = Finnish, sv = Swedish',

  'locale.overview': 'Locale usage overview',
  'locales.content': 'Page in this locale has content',
  'locales.nocontent': 'Page in this locale has no content',
  'locales.nopage': 'There is no page for this locale in this Article',
  'locales.label.table.locale': 'Language code',

  'newpage.title': 'Create a new page',
  'newpage.info': 'A page consists of localised content and must be associated with an Article.',
  'newpage.article.info': 'Confirm creation of page for: {article} with locale: {locale}',

  'page.create': 'Create page',
  'pages.save': 'Save pages',
  'pages.add': 'Add a page',
  'pages.change': 'Change a page locale',
  'pages.change.info': 'Select a page from this Article and enter a new value for its locale.',
  'pages.delete': 'Delete a page',
  'pages.delete.message': 'Select a page to delete from this Article.',
  'pages.options': 'Page options',
  'pages.edit.selectpage': 'Select page',
  'pages.edit.selectTargetLocale': 'Select target locale',

  'release.create': 'Create release',
  'release.composer.title': 'Create a new release',
  'release.composer.label': 'Tag Name',
  'release.composer.note': "Note",
  'release.composer.helper': 'Optional additional information for future reference',
  'release.desc': 'View all releases and download all site content in JSON format. For more detailed information on specific releases and their content, view the Graph.',


};

export default en;
