const en = {

  'associations.add': 'Associate with an article',
  'locale': 'Locale',
  'locales': 'Locales',
  'value': 'Value',
  'date': 'Date',
  'order': 'Order',
  'pages': 'Pages',
  'articles': 'Articles',
  'description': 'Description',
  'delete': 'Delete',
  'download': 'Download JSON',
  'disable': 'Disable',
  'status': 'Status',
  'tag': 'Tag',
  'created': 'Created',
  'modified': 'Modified',
  'releases': 'Releases',
  'options': 'Options',
  'links': 'Links',
  'workflows': 'Workflows',
  
  'explorer.pages': 'Pages',
  'explorer.pages.create': 'Create Page',
  'explorer.pages.dualview': 'Dual View',
  'explorer.locale.empty': 'No Locales',

  'article.composer.title': 'Create new Article',
  'article.composer.parent': 'Parent Article',
  'article.composer.parent.unselected': 'None',
  'article.composer.orderhelper': 'Number for menu ordering purposes',
  'article.name': 'Article name',
  'articles.message': 'Expand rows to view Pages associated with Articles and modify these associations',
  'article.delete.title': 'Permanently delete this Article?',
  'article.delete': 'Deleting this article will remove it and its associated pages globally from the application.',
  'article.deletepage.title': 'Delete this page?',
  'article.deletepage': 'Deleting this page will permanently remove it from the application.',
  
  'article.edit.title': 'Edit article',
  'article.edit.parent': 'Parent article',
  'article.edit.orderhelper': 'Three-digit number for ordering purposes',


  'button.cancel': 'Cancel',
  'button.create': 'Create',
  'button.add': 'Add',
  'button.update': 'Update',
  'button.delete': 'Continue and delete',
  'button.disable': 'Continue and disable',
  'button.enable': 'Continue and enable',
  'button.remove': 'Continue and remove',

  'composer.article.title': 'Article',
  'composer.article.desc': 'A group of associated Pages, Links, Workflows, and Locales',
  'composer.locale.title': 'Locale',
  'composer.locale.desc': 'Add, activate, and deactivate content languages globally',
  'composer.page.title': 'Page',
  'composer.page.desc': 'One file representing one language and its associated links and workflows within an Article',
  'composer.link.title': 'Link',
  'composer.link.desc': 'Internal links connect to content within your domain, and external links connect to content outside your domain',
  'composer.workflow.title': 'Workflow',
  'composer.workflow.desc': 'Connect forms and processes',
  'composer.release.title': 'Release',
  'composer.release.desc': 'Create a snapshot of all site content at one certain point of time for testing or production purposes',

  'link.associate.title': 'Associate a link with an Article',
  'link.article.add.title': 'Add link to an Article',
  'link.article.select': 'Select Article',
  'links.message': 'Expand rows to view Link - Article associations',

  
  'link.composer.title': 'Create a new link',
  'link.type': 'Type',
  'link.url': 'URL / value',
  'link.locale.all': 'All locales',
  'link.type.internal': 'Internal (within my domain)',
  'link.type.external': 'External (outside of my domain)',
  'link.type.phone': 'Phone number',
  'link.content': 'Link URL / path',
  'link.composer.descriptionlabel': 'Description',
  'link.composer.descriptionhelper': 'Text that the user will see',
  'link.composer.valuehelper': 'URL / path of link (http://www.example.com)',

  'link.edit.title': 'Edit link',
  'link.delete.title': 'Permanently delete this link?',
  'link.delete': 'Deleting this link will permanently remove it from the application, and all associations with Articles/Pages will be lost.',
  
  'link.removepage.title': 'Remove this link?',
  'link.removepage': 'Removing the link only removes its association with this article. To delete this item permanently, click the Delete icon.',

  'locale.composer.title': 'Create a new locale',
  'locale.composer.helper': 'Two-letter locale code',

  'locale.disable.title': 'Disable this locale?',
  'locale.enable.title': 'Enable this locale?',
  'locale.disable': 'Any Pages using this locale will be hidden on the UI. Pages can still be edited.',
  'locale.enable': 'All Pages using this locale will be displayed on the UI.',

  'locale.overview': 'Locale usage overview',
  'locales.content': 'Page in this locale has content',
  'locales.nocontent': 'Page in this locale has no content',
  'locales.nopage': 'There is no page for this locale in this Article',

  'newpage.title': 'Create a new page',
  'newpage.info': 'A page consists of localised content and must be associated with an Article.',
  'newpage.article.info': 'Confirm creation of page for: {article} with locale: {locale}',

  'pages.save': 'Save pages',
  
  'release.composer.title': 'Create a new release',
  'release.composer.label': 'Tag Name',
  'release.composer.note': "Note",
  'release.composer.helper': 'Optional additional information for future reference',
 
  'workflow.associate.title': 'Associate a Workflow with an Article',
  
  'workflow.composer.title': "Add a Workflow",
  'workflow.composer.name': "Localised name",
  'workflow.technicalname': 'Technical name',
  'workflow.composer.select': 'Select existing flow',
  'workflow.composer.helper': 'Name to be displayed to users',
  'workflow.composer.placeholder': 'Permit application form',

  'workflow.delete.title': 'Permanently delete this workflow?',
  'workflow.delete': 'Deleting this workflow will remove it globally from the application.',
  
  'workflow.removepage.title': 'Remove this Workflow?',
  'workflow.removepage': 'Removing the Workflow only removes its association with this article. To delete this item permanently, click the Delete icon.',

  'toolbar.articles': 'Articles overview',
  'toolbar.newarticle': 'Create new Article',
  'toolbar.newlocale': 'Add new Locale',
  'toolbar.explorer': 'Explorer',
  'toolbar.links': 'Links overview',
  'toolbar.workflows': 'Workflows overview',
  'toolbar.releases': 'Releases',
  'toolbar.locales': 'Locales',
  'toolbar.createNew': 'Create new',
};

export default en;
